version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - graphql-server

  graphql-server:
    build:
      context: .
      dockerfile: Dockerfile.graphql
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.graphql

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

